// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDv6ughHzQiAzbd8r6v0EmIx8NoFtyTmU',
    appId: '1:280887703295:web:b0e6b827ff93387fdf7eca',
    messagingSenderId: '280887703295',
    projectId: 'kyte-dt-app',
    authDomain: 'kyte-dt-app.firebaseapp.com',
    storageBucket: 'kyte-dt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RA-NZOJU8KbOvs-vFHlTaMw4gCYbbyQ',
    appId: '1:280887703295:ios:e4fa7d73472aad1fdf7eca',
    messagingSenderId: '280887703295',
    projectId: 'kyte-dt-app',
    storageBucket: 'kyte-dt-app.firebasestorage.app',
    iosBundleId: 'com.example.kyte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RA-NZOJU8KbOvs-vFHlTaMw4gCYbbyQ',
    appId: '1:280887703295:ios:e4fa7d73472aad1fdf7eca',
    messagingSenderId: '280887703295',
    projectId: 'kyte-dt-app',
    storageBucket: 'kyte-dt-app.firebasestorage.app',
    iosBundleId: 'com.example.kyte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDv6ughHzQiAzbd8r6v0EmIx8NoFtyTmU',
    appId: '1:280887703295:web:b27cfbe7e0a3b301df7eca',
    messagingSenderId: '280887703295',
    projectId: 'kyte-dt-app',
    authDomain: 'kyte-dt-app.firebaseapp.com',
    storageBucket: 'kyte-dt-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAafSMskIiSGfY4VEdk7NCnA1oEUeWw-uY',
    appId: '1:280887703295:android:a4d5d9f3ded4b0cbdf7eca',
    messagingSenderId: '280887703295',
    projectId: 'kyte-dt-app',
    storageBucket: 'kyte-dt-app.firebasestorage.app',
  );

}