import '../models/member.dart';

const List<Member> demoMembers = <Member>[
  Member(
    id: 'ceo-001',
    name: 'Aarav Sharma',
    role: 'Principal Software Engineer',
    department: 'Engineering',
    team: 'Platform',
  ),
  Member(
    id: 'eng-mgr-001',
    name: 'Ananya Verma',
    role: 'Engineering Manager',
    department: 'Engineering',
    team: 'Platform',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'eng-001',
    name: 'Rohan Mehta',
    role: 'Software Development Engineer III (SDE III)',
    department: 'Engineering',
    team: 'Core Services',
    managerId: 'eng-mgr-001',
  ),
  Member(
    id: 'eng-002',
    name: 'Ishita Rao',
    role: 'Software Development Engineer II (SDE II)',
    department: 'Engineering',
    team: 'Core Services',
    managerId: 'eng-mgr-001',
  ),
  Member(
    id: 'product-001',
    name: 'Kabir Nair',
    role: 'Product Manager',
    department: 'Product',
    team: 'Growth',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'ops-001',
    name: 'Diya Kapoor',
    role: 'DevOps Engineer',
    department: 'Operations',
    team: 'Infra',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'qa-001',
    name: 'Vikram Iyer',
    role: 'QA / Test Engineer',
    department: 'Operations',
    team: 'Quality',
    managerId: 'ops-001',
  ),
  Member(
    id: 'hr-001',
    name: 'Naina Desai',
    role: 'Technical Consultant',
    department: 'HR',
    team: 'People Ops',
    managerId: 'ceo-001',
  ),
  Member(
    id: 'mkt-001',
    name: 'Arjun Malhotra',
    role: 'Senior Software Engineer',
    department: 'Marketing',
    team: 'Brand Systems',
    managerId: 'product-001',
  ),
  Member(
    id: 'eng-003',
    name: 'Meera Joshi',
    role: 'Software Development Engineer I (SDE I)',
    department: 'Engineering',
    team: 'Platform',
    managerId: 'eng-001',
  ),
];
